name:                hdd
version:             0.1.0.0
github:              "z81/h"
license:             BSD3
author:              "Author z81"
maintainer:          "example@example.com"
copyright:           "2019 Author z81"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/z81/hdd#readme>

dependencies:
- base >= 4.7 && < 5
- warp
- network
- http-types
- wai
- blaze-builder
- utf8-string
- bytestring
- envy
- text
- process

library:
  source-dirs: src

executables:
  hdd-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hdd

tests:
  hdd-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hddz
